### ISSUE TITLE
Metadata error on some machines

### ISSUE THREAD

**Issue by srob650** [srob650/youtube_dl_interactive#10]
Trace:
```
Traceback (most recent call last):
  File "./youtube_dl_interactive.py", line 476, in <module>
    main()
  File "./youtube_dl_interactive.py", line 467, in main
    metadata = get_metadata(video_file)
  File "./youtube_dl_interactive.py", line 287, in get_metadata
    p = subprocess.Popen(proc, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by srob650** [comment]
Determined this was due to ffmpeg not installing properly on a machine.
